<template>
    <div class="container">
        <div class="container-padding">
            <div class="flex flex-column flex-align-center">
                <awesome-title title="About Me" bgColor="#1d2533" textColor="white"></awesome-title>
                <div class="flex flex-align-center" style="width: 100%">
                    <img src="../assets/me.png" class="image flex-50" alt="Wanderson Alves"/>
                    <span class="separator"></span>
                    <div class="gap flex flex-column flex-50">
                        <about-info title="name" value="Wanderson Alves Ferreira"></about-info>
                        <about-info title="e-mail" value="wandersonalvesferreira2012@gmail.com"></about-info>
                        <about-info title="hobbies" value="Rhythm Games, Prog Music, Interestellar (best movie evar), etc..."></about-info>
                    </div>
                </div>
                <div class="text-area">
                        <h4>
                            Hi, my name is Wanderson Alves, and i'm a Front-end Developer & UI/UX Designer based in Recife (Brazil). <br>
                            I am passionate about what I do, mainly because all the material generated by me is visual and interactive. <br>
                            I always stay within the new technologies, whether using them or just "knowing" that they exist. I have come across several situations where this knowledge of mine has led me forward.<br> 
                            Where I pass, I try to leave a personal touch of mine. Whether in a visual form or in code form. The people who worked with me recognize when something was done for me.
                        </h4>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
import AwesomeTitle from '@/components/AwesomeTitle.vue';
import AboutInfo from '@/components/AboutInfo.vue';

export default {
    name: 'About',
    components: {
        AwesomeTitle,
        AboutInfo
    }
}
</script>
<style lang="scss" scoped>
.container {
  min-height: 100vh;
  width: 100vw;
  padding: 65px 0;
}
.container-padding {
    padding: 0 calc(20% - 185px);
}
.image {
    width: 100%;
    height: 100%;
    vertical-align: middle;
}
.separator {
    margin-left: 30px;
    margin-right: 30px;
}
.gap {
    > div {
        margin-bottom: 20px;
    }
}

.text-area {
    margin-top: 30px;
    margin-left: 200px;
    margin-right: 200px;
}
h4 {
    font-size: 1.2em;
    letter-spacing: .03em;
    line-height: 1.5em;
    font-weight: 300;
    text-align: justify;
}
</style>


